<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 2008 R2" host="SEA-QTP2"><DocLocation><![CDATA[C:\IVM_Automation_Michael\IVM\bin\SuiteController]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SuiteController]]></DName>
<Res><![CDATA[Res20]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[SuiteController]]></AName>
<Step rID="T5">
<Obj ><![CDATA[SETUP Suite: Comprehensive]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:16]]></Time>
<TimeTick>1399025476</TimeTick>
<NodeArgs eType="User" icon="5" nRep="8" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SETUP Suite: Comprehensive]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[START Suite: Comprehensive]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:17]]></Time>
<TimeTick>1399025477</TimeTick>
<NodeArgs eType="User" icon="5" nRep="9" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[START Suite: Comprehensive]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[SETUP Flow: Scheduled_CampaignSummary]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:17]]></Time>
<TimeTick>1399025477</TimeTick>
<NodeArgs eType="User" icon="5" nRep="10" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SETUP Flow: Scheduled_CampaignSummary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[STEP: ivm.startivmBrowser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:17]]></Time>
<TimeTick>1399025477</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.startivmBrowser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:17]]></Time>
<TimeTick>1399025477</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:17]]></Time>
<TimeTick>1399025477</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" status="Passed" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Internet Explorer\iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="14" status="Passed" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:27]]></Time>
<TimeTick>1399025487</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[pgCertificateErrorNavigation]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:27]]></Time>
<TimeTick>1399025487</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[lnkContinueWebsite.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:27]]></Time>
<TimeTick>1399025487</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkContinueWebsite.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[lnkContinueWebsite.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:27]]></Time>
<TimeTick>1399025487</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkContinueWebsite.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="18" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgCertificateErrorNavigation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[STEP: ivm.logIn()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="23" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.logIn()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[STEP: ivm.page(pgLogin)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="24" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgLogin)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="25" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Username)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="26" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Username)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Username).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="27" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Username).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Username).setValue(admin)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="28" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Username).setValue(admin)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[pgLogin]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[txtUsername.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[txtUsername.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[txtUsername.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[txtUsername.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="32" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgLogin]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="31" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[STEP: ivm.page(pgLogin)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="36" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgLogin)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="37" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Password)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="38" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Password)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Password).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="39" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Password).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[STEP: ivm.IVMPage.webEdit(Password).setValue(admin@123)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="User" icon="5" nRep="40" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.webEdit(Password).setValue(admin@123)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[pgLogin]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[txtPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[txtPassword.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[txtPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin@123"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:33]]></Time>
<TimeTick>1399025493</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[txtPassword.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="44" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgLogin]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="43" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[STEP: ivm.page(pgLogin)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="User" icon="5" nRep="48" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgLogin)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="User" icon="5" nRep="49" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[STEP: ivm.IVMPage.weblink(LogIn)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="User" icon="5" nRep="50" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.weblink(LogIn)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(LogIn).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="User" icon="5" nRep="51" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(LogIn).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(LogIn).press()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="User" icon="5" nRep="52" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(LogIn).press()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[pgLogin]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[lnkLogIn.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkLogIn.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[lnkLogIn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:34]]></Time>
<TimeTick>1399025494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkLogIn.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="55" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgLogin]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="54" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[START Flow: Scheduled_CampaignSummary]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:44]]></Time>
<TimeTick>1399025504</TimeTick>
<NodeArgs eType="User" icon="5" nRep="59" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[START Flow: Scheduled_CampaignSummary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[SETUP TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:44]]></Time>
<TimeTick>1399025504</TimeTick>
<NodeArgs eType="User" icon="5" nRep="60" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SETUP TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[START TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:44]]></Time>
<TimeTick>1399025504</TimeTick>
<NodeArgs eType="User" icon="5" nRep="61" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[START TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[SETUP TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:44]]></Time>
<TimeTick>1399025504</TimeTick>
<NodeArgs eType="User" icon="5" nRep="62" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SETUP TestCase: ScheduleNewReport_CampaignSummary_ValidateSiteGroups]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[STEP: ivm.NavigateToMenu(Data Analytics > Reports > Scheduled Reports)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="63" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.NavigateToMenu(Data Analytics > Reports > Scheduled Reports)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[STEP: ivm.page(pgCommon)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="64" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgCommon)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="65" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[STEP: ivm.IVMPage.weblink(DataAnalytics)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="66" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.weblink(DataAnalytics)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(DataAnalytics).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="67" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(DataAnalytics).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(DataAnalytics).press()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="User" icon="5" nRep="68" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(DataAnalytics).press()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[pgCommon]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[lnkDataAnalytics.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkDataAnalytics.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[lnkDataAnalytics.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:45]]></Time>
<TimeTick>1399025505</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkDataAnalytics.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="71" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgCommon]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="70" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[STEP: ivm.page(pgCommon)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:55]]></Time>
<TimeTick>1399025515</TimeTick>
<NodeArgs eType="User" icon="5" nRep="75" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgCommon)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:55]]></Time>
<TimeTick>1399025515</TimeTick>
<NodeArgs eType="User" icon="5" nRep="76" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[STEP: ivm.IVMPage.weblink(Reports)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:55]]></Time>
<TimeTick>1399025515</TimeTick>
<NodeArgs eType="User" icon="5" nRep="77" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.weblink(Reports)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(Reports).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:55]]></Time>
<TimeTick>1399025515</TimeTick>
<NodeArgs eType="User" icon="5" nRep="78" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(Reports).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(Reports).press()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:56]]></Time>
<TimeTick>1399025516</TimeTick>
<NodeArgs eType="User" icon="5" nRep="79" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(Reports).press()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:56]]></Time>
<TimeTick>1399025516</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[pgCommon]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:56]]></Time>
<TimeTick>1399025516</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[lnkReports.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:56]]></Time>
<TimeTick>1399025516</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="83" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkReports.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[lnkReports.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:41:56]]></Time>
<TimeTick>1399025516</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[lnkReports.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="82" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[pgCommon]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="81" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[SeaChangeManagementConsole]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[STEP: ivm.page(pgCommon)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<NodeArgs eType="User" icon="5" nRep="86" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.page(pgCommon)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<NodeArgs eType="User" icon="5" nRep="87" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[STEP: ivm.IVMPage.weblink(ScheduledReports)]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<NodeArgs eType="User" icon="5" nRep="88" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.weblink(ScheduledReports)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(ScheduledReports).internal_assign()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<NodeArgs eType="User" icon="5" nRep="89" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(ScheduledReports).internal_assign()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj ><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(ScheduledReports).press()]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<NodeArgs eType="User" icon="5" nRep="90" Source="SuiteController" SourceLine="26" >
<Disp><![CDATA[STEP: ivm.IVMPage.WebLinkProxy(ScheduledReports).press()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[SeaChangeManagementConsole]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[pgCommon]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-05-02 - 15:42:06]]></Time>
<TimeTick>1399025526</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[lnkScheduledReports.Exist]]></Obj>